apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spark-master
spec:
  replicas: 1
  template:
    metadata:
      labels:
        spark: master
    spec:
        containers:
          - name: spark-master-container
            image: registry.eu-gb.bluemix.net/brunocf_containers/spark2_2:latest
            command: ["/home/spark/spark-2.2.0-bin-hadoop2.7/bin/spark-class","org.apache.spark.deploy.master.Master"]
            ports:
            - name: spark-clu-port
              containerPort: 7077
            - name: spark-m-ui-port
              containerPort: 8080
            volumeMounts:
                - mountPath: /home/spark/jobs
                  name: jobs-vol
        volumes:
        - name: jobs-vol
          persistentVolumeClaim:
              claimName: spark-jobs
